### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [ms-jpq/sad#10]
Hey there,

I was thinking of creating an AUR package for this but I see that you have not specified a software license yet.

Could you let me know if I could package this and if so, under what license? 

(You would probably have to provide it with your project as well) 

Cheers

**Comment by ms-jpq** [comment]
Hi there,

I just want everybody to be able to use this, do you have a license in mind? I don't know which one to add

**Comment by ms-jpq** [comment]
Ok i just added MIT, since thats what somebody else told me to do

https://github.com/ms-jpq/sad/blob/senpai/LICENSE

**Comment by MadeOfMagicAndWires** [comment]
Thanks for the quick response

If you just want to make it as easy as possible to make use of your project MIT is indeed a good choice for that, and I think most Rust projects also use this license.

If you want to know more about open source licenses you can find more info on the most popular ones  [here](https://choosealicense.com/licenses/) but to quickly run down the two types of licenses:

+ **Permissive licenses** (like the MIT) basically put as little restrictions upon the user as possible. They allow use, modification, and distribution of software and really only require a copy of the license (with copyright notice) to be included with any copy of source code or binaries based on it (that last one is where I come in).

+ **Copyleft licenses** (like GPL) are a bit more restrictive in that they try to protect their software a bit more. GPL for example requires any modifactions of the software to be released under the same license and that they are made publicly available; thus keeping improvements within the opensource ecosystem.

As per the terms of service of Github any pull requests are released under the same license, regardless of whether that license requires that, but users are allowed to view and fork code of public repositories **even if you have not provided a LICENSE file**.   

Should you ever want to change the license you as the owner can, but others can only choose to provide any forks under more restrictive licenses, as long as the terms the original license are met as well.

Anyway, thanks for the license, I'll let you know once I've uploaded the package

**Comment by ms-jpq** [comment]
@MadeOfMagicAndWires ,

Thank you for the explanation, as for the AUR thing, is there anything I can help with?

I actually don't know anything about how AUR works, but I assume I can make your life easier by adding some AUR specific artifacts on my CI?

**Comment by MadeOfMagicAndWires** [comment]
Hm, I don't think you  to go as far as compiling packages. You can always link to it in the `README` if you want though.

Basically the [Arch User Repository](https://aur.archlinux.org/) is for "unofficial" packages, the main difference is  that while the official repositories provide binary packages like most distro's the AUR "package" exists out of [`PKGBUILD`](https://wiki.archlinux.org/index.php/PKGBUILD) files. 

PKGBUILD files are basically pseudo-scripts which can be used to compile and build Arch packages from source code using `makepkg`. This is mostly done to reduce storage space (presumably) and to allow Unofficial packages to be created for Arch beyond the official list, and without the Arch Linux team being responsible for maintaining them. 

Compiling binaries at runtime is preferred over providing pre-compiled binaries with the PKGBUILD file because that ensures the binaries always conform to the hardware and settings of that user.  
You'll really only see some `-bin` packages, containing pre-compiled binaries, when the source-code is not available, or if compiling takes some serious calculating power. 

So I guess you could set CI up to also build binary Arch packages like with the .deb package (a quick search provides [this](https://bbs.archlinux.org/viewtopic.php?id=243393) [*] discussion on the topic), but most users will probably still prefer manually building the package through the AUR by default.

[*]: I've never used CI myself, but at a quick glance this seems usable, the main difference is that `makepkg` compresses the packages using `zstd` rather than `xr` by default now, so you would have to edit any references to `.tar.xz` files with `.tar.zst` files now, or provide a makepkg config file if you desperately still want to use the `xz` format.

**Comment by ms-jpq** [comment]
If you want I can give you read / write permission to this repo? So it would make your life easier.

and again, thanks for the detailed explaination

**Comment by MadeOfMagicAndWires** [comment]
Thanks for offering! 

I won't need write permission to the repository. I'm now watching this repo for releases, which is pretty much all I need to keep the package updated. 

As for something else, unless you had something specific in mind I'm not sure I can offer much, as I've never worked with Rust as of yet.

If I ever manage contribute to the project beyond packaging though, I can always just do that through Pull Requests as well.
