### ISSUE TITLE
Missing Cargo.lock file

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [ms-jpq/sad#11]
Hey there, it's me again.

This is not required to create a package, but using a [Cargo.lock](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html) file over a regular Cargo.toml file helps creating reproducible builds of packages.

I've never used CI myself but I assume you can easily use it there as well.

**Comment by ms-jpq** [comment]
No problem, I will add one the next release, coming soon :)

Need to test a few things first.

**Comment by MadeOfMagicAndWires** [comment]
Cheers!

And yeah, take your time, there's no real hurry with this one, code compiles fine. It's just like a nice extra feature that assures everyone is using the exact same code for the dependencies.

**Comment by ms-jpq** [comment]
Haha, thank you for pushing me to the best practice on this, my plan was just to leave it for the daily CI to catch any build errors.

:)

**Comment by ms-jpq** [comment]
@MadeOfMagicAndWires 

I added https://github.com/ms-jpq/sad/blob/senpai/Cargo.lock the cargo file you wanted.

I also made it so that if it detects `fzf` or `delta` or `diff-so-fancy`, `sad` will automatically use them. So in your AUR package, you can list `fzf` + `delta` as a requirement, and `sad` will require zero setup from the users.

**Comment by MadeOfMagicAndWires** [comment]
Thanks a bunch! 

I had added `fzf`, `delta`, and `diff-so-fancy` as (optional) dependencies; does  `sad` still work without those being installed or are these now hard dependencies?

**Comment by ms-jpq** [comment]
@MadeOfMagicAndWires,

They are optional dependencies, but they REALLY improve how `sad` is used.

For example:

The selection UI here is purely done from `sad` generating instructions for `fzf`, `sad` isn't even aware of the GUI.

![example1.gif](https://raw.githubusercontent.com/ms-jpq/sad/senpai/previews/preview1.gif)

Same thing with the syntax highlighted diff.

`sad` is only generating instructions for `delta` and `diff-so-fancy`. It by itself, does not perform any colouring.

I think the user expereince with `fzf` and one of `delta` + `diff-so-fancy` is so much better to the point where I think they might as well be hard dependencies.

---

I basically wrote `sad` as a program that generations instructions for other programs, including instructions for other programs to call `sad` with. i.e. `sad` -> `fzf` -> `sad`

**Comment by ms-jpq** [comment]
AHHHHHHHHHHHHH DAMMIT,

ive been mindlessly merging in dependa-bot commits and didnt realize `async-std` `1.9` broke the build...

would this affect your thingy?

I will try to fix this ASAP. embarrassing :<

**Comment by MadeOfMagicAndWires** [comment]
Sorry about the late reply, this flew under the radar for quite a while.

I am happy to report that everything still builds fine. That said, there is a small bug, which is that the version number in the `Cargo.lock` was not updated for the 0.4.7 tag.

This isn't really an issue anymore for the senpai branch; the version number was bumped in here
https://github.com/ms-jpq/sad/blob/0177e963cffae10c93510786256412d34675eeb5/Cargo.lock#L707

but for anyone downloading the 0.4.7 release and trying to build with the `--locked` flag it will throw an error and they'd have run it without the flag or run `cargo update` first. 

Now I'm not really sure how often this use-case will happen, `--locked` is only used for reproducible builds, or what would be the best way to fix this. You could forcibly move the 0.4.7 tag to link to 0177e963cf or later, but considering you've commited unrelated work in-between you might just want to wait until you make a new release. 

For the package I think I'll just apply a small patch to the `Cargo.lock` file beforehand so you won't have to do anything on my accord, and I think other users will just download the CI builds, which should work fine, so I don't think you need to take any drastic actions.

Long post, but thanks for all the work!
