### ISSUE TITLE
Failed to work on linux /dev/stdin error

### ISSUE THREAD

**Issue by ray-x** [ms-jpq/sad#118]
It seems not working on linux (archlinux)
I tried the latest version and release version. Both have the following errors:

```
Error:
ArgumentError(
    "/dev/stdin connected to tty",
)
```

**Comment by zach-is-my-name** [comment]
I got the same thing.  I think it only works with a stdin like` fd .. | sad arg arg`.  possibly to select which files it should target for search and replace instead of defaulting to the current directory

**Comment by jm-janzen** [comment]
Thanks @zach-is-my-name. It was entirely a pebkac error. Using `sad` as instructed and it works exactly as designed.

**Comment by wakywayne** [comment]
How did you guys install it on linux npm???

**Comment by ray-x** [comment]
@wakywayne  I was using `yay` on archlinux.
As for the issue itself zach is correct.
