### ISSUE TITLE
reproducible builds issue

### ISSUE THREAD

**Issue by bmwiedemann** [ms-jpq/sad#359]
While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds) (sponsored by the NLnet NGI0 fund), I found that
our `sad` package varied in every build, because
https://github.com/ms-jpq/sad/blob/6c65d52211e79298c0e1b1496a7287e98cb8e813/build.rs#L18
adds randomness into the binary.

Why are these UUIDs random? Could they be made a hash over some relevant build input? Or be dropped/replaced with something deterministic?

**Comment by ms-jpq** [comment]
sure i can do that!

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/sad/commit/c5040be870834f9956e61f2eb1521e0f2a7ed481

The randomness was entirely due to basically generating a env var name that will never clash, i just took it out and added hard coded ones
