### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by ntpeters** [ms-jpq/sad#98]
Currently trying to build on Windows fails with the following errors:

```powershell
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> src\input.rs:14:7
   |
14 |   os::unix::ffi::OsStringExt,
   |       ^^^^ could not find `unix` in `os`

error[E0599]: no function or associated item named `from_vec` found for struct `OsString` in the current scope
   --> src\input.rs:165:48
    |
165 |             let path = PathBuf::from(OsString::from_vec(buf));
    |                                                ^^^^^^^^ function or associated item not found in `OsString`
```

Building from source with:
```
cargo install --locked --all-features --git https://github.com/ms-jpq/sad --branch senpai
```

**Comment by ms-jpq** [comment]
humm in theory this should work under windows, i just need to add the path parsing code for it, but it wont be nearly as hassle free to set up, so ill need to add it in the README

**Comment by ms-jpq** [comment]
mostly because it needs things to be in %PATH%, or the users have to specify absolute path.

which is a PITA on windows

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/sad/releases/tag/v0.4.15

might work?

i dunno

**Comment by ms-jpq** [comment]
ok nvm, it can't pass the tests on windows, for some reason linux is ok.

i guess that will just require more fiddling around in a windows vm.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/sad/pull/102
